# Generated by Django 3.1.5 on 2021-01-26 10:41

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=132)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shikoyat mavzusi',
                'verbose_name_plural': 'Shikoyat mavzusi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Majlis mavzusi')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish Vaqti')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Tugash Vaqti')),
                ('organizer', models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi')),
                ('organizer_position', models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi lavozimi')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Reja qilingan'), (2, 'Jarayonda'), (3, 'Yakunlangan'), (4, 'Bekor qilingan')], default=1, verbose_name='Holati')),
                ('approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('participant_number', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('count_approved', models.BooleanField(default=False, verbose_name='Ishtirokchi soni tasdiqlandi')),
                ('date_approved', models.BooleanField(default=False, verbose_name='sana tasdiqlandi')),
            ],
            options={
                'verbose_name': 'Majlis',
                'verbose_name_plural': 'Majlislar',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=132)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
            },
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=132)),
            ],
            options={
                'verbose_name': 'Ishtirokchi turi',
                'verbose_name_plural': 'Ishtirokchi turlari',
            },
        ),
        migrations.CreateModel(
            name='MeetingTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Majlis mavzusi')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meeting', verbose_name='Majlis')),
            ],
            options={
                'verbose_name': 'Majlis mavzusi',
                'verbose_name_plural': 'Majlis mavzulari',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participant_type',
            field=models.ManyToManyField(to='main.ParticipantType'),
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('comment', models.TextField(blank=True, null=True)),
                ('show_contact', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqami')),
                ('checked', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meeting')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.complianceoption')),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(error_messages={'unique': 'Bu foydalanuvchi nomi allaqachon mavjud.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('full_name', models.CharField(blank=True, max_length=128, verbose_name="To'liq ism")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana")),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Oxirgi aktiv holati')),
                ('phone', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='13-ta raqamgacha ruxsat berilgan.', regex='^\\d{9}$')], verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Tashkilot')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', main.manager.UserManager()),
            ],
        ),
    ]
