# Generated by Django 3.1.1 on 2021-02-02 08:50

import os
import json
from django.db import migrations

from main.models import Region
from core.settings import BASE_DIR


def load_regions(apps, scheme_editor):
    with open(os.path.join(BASE_DIR, 'main/assets/common_region.json'), encoding="utf8", errors='ignore') as json_file:
        data = json.load(json_file)
        for region in data:
            Region.objects.create(id=region['id'],  title=region['name'], title_ru=region['name_ru'],
                                  title_uz=region['name_uz'])


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_region'),
    ]

    operations = [
        migrations.RunPython(load_regions, reverse_func)
    ]
