# Generated by Django 3.1.1 on 2021-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='comment_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceoption',
            name='name_ru',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='complianceoption',
            name='name_uz',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='comment_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer_position_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi lavozimi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer_position_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi lavozimi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Majlis mavzusi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Majlis mavzusi'),
        ),
        migrations.AddField(
            model_name='meetingtopic',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Majlis mavzusi'),
        ),
        migrations.AddField(
            model_name='meetingtopic',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Majlis mavzusi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_uz',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='participanttype',
            name='name_ru',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='participanttype',
            name='name_uz',
            field=models.CharField(max_length=132, null=True),
        ),
    ]
