# Generated by Django 3.1.1 on 2021-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210202_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='main.region', verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to='main.organization', verbose_name='Tashkilot'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='meeting',
            field=models.ForeignKey(on_delete=models.SET(0), to='main.meeting'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='option',
            field=models.ForeignKey(on_delete=models.SET(0), to='main.complianceoption'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(on_delete=models.SET(0), to='main.organization', verbose_name='Tashkilot'),
        ),
        migrations.AlterField(
            model_name='meetingtopic',
            name='meeting',
            field=models.ForeignKey(on_delete=models.SET(0), to='main.meeting', verbose_name='Majlis'),
        ),
    ]
