# Generated by Django 3.1.1 on 2021-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210202_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='user_organization', to='main.organization', verbose_name='Tashkilot'),
        ),
    ]
