# Generated by Django 3.1.1 on 2021-02-04 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210204_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to=settings.AUTH_USER_MODEL, verbose_name='Masul'),
        ),
    ]
