# Generated by Django 3.1.1 on 2021-02-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210205_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.meeting'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.complianceoption'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization', verbose_name='Tashkilot'),
        ),
        migrations.AlterField(
            model_name='meetingtopic',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.meeting', verbose_name='Majlis'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Region'),
        ),
    ]
