# Generated by Django 3.1.1 on 2021-02-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210208_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='user',
            new_name='organization',
        ),
    ]
