# Generated by Django 3.1.1 on 2021-02-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210208_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Tashkilot'),
        ),
    ]
