# Generated by Django 3.1.1 on 2021-02-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210208_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Tashkilot'),
            preserve_default=False,
        ),
    ]
