# Generated by Django 3.1.1 on 2021-02-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210208_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='regionadmin',
            field=models.BooleanField(default=False, verbose_name='Regional Admin'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='organization',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Tashkilot'),
            preserve_default=False,
        ),
    ]
