# Generated by Django 3.1.1 on 2021-02-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210216_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Region'),
        ),
    ]
