# Generated by Django 3.1.5 on 2021-02-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210216_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Tashkilot'),
        ),
    ]
