# Generated by Django 3.1.5 on 2021-02-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_meeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='comment_uz',
        ),
        migrations.RemoveField(
            model_name='complianceoption',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='complianceoption',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='comment_uz',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer_position_ru',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer_position_uz',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer_ru',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer_uz',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='meetingtopic',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='meetingtopic',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='participanttype',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='participanttype',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='region',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='title_uz',
        ),
    ]
