# Generated by Django 3.1.5 on 2021-02-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210224_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participant_type',
        ),
        migrations.AddField(
            model_name='meeting',
            name='participant_type',
            field=models.CharField(max_length=128, null=True, verbose_name='Tashkilotchi'),
        ),
        migrations.DeleteModel(
            name='ParticipantType',
        ),
    ]
