# Generated by Django 3.1.5 on 2021-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210327_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTelegramID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=256, verbose_name='Adminni ismi')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, verbose_name='Telegram Token')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
